version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8765:8765"
    networks:
      - app_network

  client-builder:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app_network
    volumes:
      - ./client/dist:/dist

networks:
  app_network:
    driver: bridge